baseURL = '/'
languageCode = 'en-us'
title = 'Subfly Dev Portfolio'
theme = 'typo'

[params]
theme = 'dark'
homeIntroTitle = 'Hi! I am Ali Taha Dinçer a.k.a. Subfly Dev'
homeIntroContent = '''
I am a **Mobile Application Developer** based in Munich, Germany, currently pursuing my Master's degree in Informatics at the Technical University of Munich while working as a Working-Student at Check24.

## 🚀 What I Do

I focus on **all types of mobile development**, with specialized expertise in **Android development** using modern technologies like **Jetpack Compose** and **Kotlin Multiplatform**. My journey started in 2017, and since then I've:

- **Worked on apps** with millions of downloads
- **Pioneered Compose transitions** for major Turkish companies (Pegasus Airlines, Bundle)
- **Worked on AI/ML projects** including real-time ASL translation
- **Created open source projects** like YABA

## 🎯 Current Focus

- **M.Sc. in Informatics** at Technical University of Munich
- **Working-Student** at Check24
- **Open source development** with privacy-focused applications
- **Teaching and collaboration** opportunities

## 💼 Experience Highlights

- **Commencis** (2023-2024): Enhanced Pegasus Airlines' Android app (10M+ downloads)
- **Bundle** (2022-2023): Re-implemented Turkey's leading news app (2M+ downloads)
- **Somera** (2020-2022): Server-side development with AI/ML focus

## 🛠️ Technologies

**Mobile**: Kotlin, Jetpack Compose, Java, Swift, SwiftUI, Flutter, React Native
**Server-side**: Spring Boot, Python, TensorFlow, Ktor
**Tools**: GitLab CI, Docker, Adobe XD

*I'm always open to collaborating on interesting projects and sharing knowledge through talks and teaching.*
'''
paginationSize = 100
colorPalette = 'default'

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "blog"
url = "/posts"

[[params.menu]]
name = "yaba"
url = "/posts/yaba"

[[params.social]]
name = "github"
url = "https://github.com/subfly"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/ali-taha-dincer/"

[[params.social]]
name = "twitter"
url = "https://x.com/AliTahaSubfly"

[[params.social]]
name = "medium"
url = "https://medium.com/@alitahasubfly"

[[params.social]]
name = "reddit"
url = "https://www.reddit.com/user/SubflyDev/"

[[params.social]]
name = "email"
url = "mailto:alitaha@subfly.dev" 